# Docs: https://confluence.atlassian.com/x/14UWN

# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.1.2

clone:
  depth: full

pipelines:
  default:
    - step:
        script:
          - npm install
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
