version: 2

jobs:
  build:
    working_directory: ~/scam # Should match where repo is cloned (i.e. GitHub project name)
    docker:
      - image: circleci/node:8.1.2 # Use the Docker image with the right node version, should match .nvmrc: https://hub.docker.com/r/circleci/node/tags/
    steps:
      - checkout # Clone repo
      # - setup_remote_docker # Ensure Docker commands are available
      - run:
          name: dependencies # Install dependencices
          command: npm install
      # - run:
      #     name: test # Run tests
      #     command: npm run test
      # - run:
      #     name: deploy
      #     command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
  deployment:
    production:
      branch: master
      heroku:
        appname: scam-demo
